name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your input! This project is based on fantastic collaborations such as yours!'' first issue'
        pr-message: 'Thank your your PR, we will take a few days to review it, and it everything is in order we will merge it!'' first pr'
